### ISSUE TITLE
Fedora 23: traceback when attempting to use freerdp

### ISSUE THREAD

**Issue by scottlinux** [robled/rocket-depot#81]
rdesktop works ok, but selecting freerdp results in an exception:

<pre>
[smiller@scottbookpro ~]$ rocket-depot 
/usr/bin/rocket-depot:12: PyGIWarning: GdkPixbuf was imported without specifying a version first. Use gi.require_version('GdkPixbuf', '2.0') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, GdkPixbuf, Gtk
/usr/bin/rocket-depot:12: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, GdkPixbuf, Gtk
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 813, in __bootstrap_inner
    self.run()
  File "/usr/bin/rocket-depot", line 238, in run
    p = subprocess.Popen(self.cmdline, stderr=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
</pre>

<pre>
[smiller@scottbookpro ~]$ cat /etc/redhat-release 
Fedora release 23 (Twenty Three)
</pre>

<pre>
[smiller@scottbookpro ~]$ which xfreerdp
/usr/bin/xfreerdp
</pre>

<pre>
[smiller@scottbookpro ~]$ python --version
Python 2.7.10
</pre>

**Comment by robled** [comment]
Try out this new code.  In the meantime I need to fix my GPG stuff before I can upload a new version to pypi.

**Comment by scottlinux** [comment]
+1 

GTK warning gone. Still doesn't like freerdp. 

<pre>
[smiller@scottbookpro ~]$ rocket-depot
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 813, in __bootstrap_inner
    self.run()
  File "/usr/bin/rocket-depot", line 245, in run
    p = subprocess.Popen(self.cmdline, stderr=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
</pre>

**Comment by robled** [comment]
Run it again with --debug on the CLI and paste the output.

**Comment by scottlinux** [comment]
Ah, my apologies. No xterm installed.

<pre>
[smiller@scottbookpro ~]$ rocket-depot --debug
debugging enabled
Command to execute:
xterm -hold -e /usr/bin/xfreerdp +clipboard /u:BANDWIDTHLOCAL\smiller /size:1024x768 -grab-keyboard /v:192.168.7.41
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 813, in __bootstrap_inner
    self.run()
  File "/usr/bin/rocket-depot", line 245, in run
    p = subprocess.Popen(self.cmdline, stderr=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
</pre>


<pre>
[smiller@scottbookpro ~]$ which xfreerdp
/usr/bin/xfreerdp

[smiller@scottbookpro ~]$ which xterm
/usr/bin/which: no xterm in (/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/smiller/.local/bin:/home/smiller/bin)
</pre>

**Comment by robled** [comment]
Still a bug.  I need to do a few things:

* use the default terminal instead of requiring xterm
* provide an error message if a program is missing
* find the full path to the default terminal

**Comment by robled** [comment]
Fedora packages get us closer here, but I still need to do dependency checking for PyPI users.

7c3f809921530cea805160df8373827dd112761a

**Comment by robled** [comment]
I'm in Fedora now!

https://apps.fedoraproject.org/packages/rocket-depot

**Comment by scottlinux** [comment]
Close me

**Comment by robled** [comment]
Negative, you need to submit a pull request that checks for dependencies when installed via pip!
